TASK1

CREATE TABLE USERS( USER_ID NUMBER(10) PRIMARY KEY, USERNAME VARCHAR2(30) UNIQUE,PASSWORD VARCHAR2(20),Email varchar2(30));
CREATE TABLE TRAINS(
    TRAIN_NO NUMBER(10) PRIMARY KEY,
    TRAIN_NAME VARCHAR2(50),
    SOURCE VARCHAR2(50),
    DESTINATION VARCHAR2(50),
    SEATS NUMBER(8)
);
CREATE TABLE RESERVATIONS (
    PNR NUMBER(20) PRIMARY KEY,

    USER_ID NUMBER(10) NOT NULL,

    PASSENGER_NAME VARCHAR2(50) NOT NULL,

    TRAIN_NO NUMBER(10) NOT NULL,

    CLASS_TYPE VARCHAR2(20) NOT NULL,

    JOURNEY_DATE DATE NOT NULL,

    SOURCE_STATION VARCHAR2(50) NOT NULL,

    DESTINATION_STATION VARCHAR2(50) NOT NULL,

    FARE NUMBER(8,2) NOT NULL,

    CONSTRAINT FK_RES_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_RES_TRAIN
        FOREIGN KEY (TRAIN_NO)
        REFERENCES TRAINS(TRAIN_NO)
);

CREATE TABLE TRAIN_FARE(
    TRAIN_NO NUMBER(10),
    CLASS_TYPE VARCHAR2(20),
    FARE NUMBER(8,2),
    PRIMARY KEY(TRAIN_NO, CLASS_TYPE),
    FOREIGN KEY(TRAIN_NO) REFERENCES TRAINS(TRAIN_NO)
);

CREATE SEQUENCE PNR_SEQ
START WITH 100001
INCREMENT BY 1
NOCACHE
NOCYCLE;
